---
title: "Do Perceptions of Remaining Life Shape Procrastination? Evidence from Latent Class and Bayesian Models"
date: 2026-03-27
author:
  - name: Cormac Monaghan
    url: "https://c-monaghan.github.io/"
    orcid: 0000-0001-9012-3060
    affiliation:
      - Hamilton Institute, Maynooth University
      - Department of Psychology, Maynooth University
  - name: Ciarán Gartlan
    url: https://www.linkedin.com/in/ciar%C3%A1n-gartlan-957426230/
    affiliation:
      - Department of Psychology, Maynooth University
  - name: Rafael de Andrade Moral
    url: https://rafamoral.github.io/
    orcid: 0000-0002-0875-3563
    affiliation:
      - Department of Mathematics and Statistics, Maynooth University
  - name: Joanna McHugh Power
    url: https://www.maynoothuniversity.ie/people/joanna-mchugh-power
    orcid: 0000-0002-7387-3107
    affiliation:
      - Department of Psychology, Maynooth University
categories:
  - procrastination
  - ageing
  - life expectancy
  - bayesian
pub-info:
  reference: >-
    <strong>Monaghan, C</strong>, <a href="https://www.linkedin.com/in/ciar%C3%A1n-gartlan-957426230/">Gartlan, C</a>, <a href="https://rafamoral.github.io/">de Andrade Moral, R</a>, & <a href="https://www.maynoothuniversity.ie/people/joanna-mchugh-power">McHugh Power, J</a>. Do Perceptions of Remaining Life Shape Procrastination? Evidence from Latent Class and Bayesian Models.
  links:
    - name: Preprint
      url: https://c-monaghan.github.io/fearless-leader/manuscript/output/manuscript.pdf
      icon: fa-solid fa-file-pdf
    - name: Code
      url: https://github.com/C-Monaghan/fearless-leader
      icon: fa-brands fa-github
pub-status:
  status: Writing
  class: warning
  icon: fa-solid fa-pencil
---

## Important links

- [Paper (preprint)](https://c-monaghan.github.io/fearless-leader/manuscript/output/manuscript.pdf)
- [Statistical analysis notebook](https://c-monaghan.github.io/fearless-leader/)
- [Github repository](https://github.com/C-Monaghan/fearless-leader/)

## Abstract

Procrastination is linked to temporal orientation, with stronger future orientation typically associated with lower procrastination. However, it remains unclear whether subjective remaining life is associated with procrastination. This study examined associations between temporal orientation, subjective remaining life, and procrastination in a sample of 140 adults aged 18–77. Latent class analysis identified two temporal profiles: a high future orientation group (46.43%) and a neutral orientation group (53.37%). Bayesian regression indicated that higher subjective remaining life was likely associated with greater procrastination, although the effect was modest. In contrast, future orientation showed a clear negative association with procrastination. These findings suggest that subjective remaining life may function as a contextual factor, whereas temporal orientation represents a more robust correlate of procrastination.
