---
title: "Procrastination as a Marker of Cognitive Decline: Evidence from Longitudinal Transitions in the Older Adult Population"
author:
  - name: Cormac Monaghan
    url: https://c-monaghan.github.io/
    orcid: 0000-0001-9012-3060
    github: https://github.com/C-Monaghan/Procrastination_Health
    affiliation: Maynooth University
  - name: Rafael de Andrade Moral
    orcid: 0000-0002-0875-3563
    affiliation: Maynooth University
  - name: Michelle Kelly
    orcid: 0000-0001-6159-6707
    affiliation: National College of Ireland
  - name: Joanna McHugh Power
    orcid: 0000-0002-7387-3107
    affiliation: Maynooth University
categories:
  - procrastination
  - dementia
  - health
  - cognitive decline
  - ageing
pub-info:
  links:
    - name: Preprint
      url: https://c-monaghan.github.io/crisp-clam/analysis/manuscript.html
      icon: fa-solid fa-file-pdf
    - name: Code
      url: https://github.com/C-Monaghan/crisp-clam
      icon: fa-brands fa-github
    - name: Analysis notebook
      url: https://c-monaghan.github.io/crisp-clam/
      icon: fa-solid fa-chart-simple
  reference: >-
    <a href="https://github.com/C-Monaghan">Monaghan, C.</a>, de Andrade Moral, R, Kelly, M, & McHugh Power, J. Procrastination as a Marker of Cognitive Decline: Evidence from Longitudinal Transitions in the Older Adult Population.
pub-status:
  status: Writing
  class: warning
  icon: fa-solid fa-pencil
---

## Important links

- [Paper (preprint)](./files/ALZ_2025.pdf){target="_blank"}
- [Statistical analysis notebook](https://c-monaghan.github.io/crisp-clam/){target="_blank"}
- [GitHub repository](https://github.com/C-Monaghan/crisp-clam){target="_blank"}

## Abstract

Cognitive decline is a global health concern, making the identification of early, modifiable risk factors essential. While apathy is a recognized prodromal marker, procrastination may also signal early executive dysfunction. We used longitudinal secondary data from the United States Health and Retirement Study among adults aged 60+ $(n = 549; \bar{x} = 69.70;\sigma = 7.58)$. Cognitive function, procrastination, and a proxy measure of apathy were assessed. Transitions between normative cognitive function, mild cognitive impairment (MCI), and dementia were modeled using a discrete-time first-order Markov model. Procrastination scores were higher among individuals with MCI or dementia than those with normative cognitive function. Procrastination also interacted with age, disproportionately increasing the risk of decline in the oldest participants. Procrastination was associated with cognitive impairment and predicted transitions to MCI, suggesting it may serve as both an early behavioral marker and compounding risk factor.

## BibTeX citation

```bibtex
@unpublished{monaghan2025,
    Author = {Cormac Monaghan, de Andrade Moral, Rafael, Kelly, Michelle, and Power, Joanna McHugh},
    Note = {Working paper},
    Title = {Procrastination as a Marker of Cognitive Decline: Evidence from Longitudinal Transitions in the Older Adult Population},
    Year = {2025}}
```
