---
title: "What We Talk About When We Talk About the Past: Discursive Psychological Analysis of Autobiographical Reminiscence in Older Irish Adults"
type: "article"
author: 
  - name: "Andrew P. Allen"
    affiliation: 
      - "Department of Psychology, Maynooth University, Ireland"
      - "School of Nursing and Midwifery, Trinity College Dublin, Ireland"
  - name: "Caoilainn Doyle"
    affiliation: "Department of Psychology, Maynooth University, Ireland"
  - name: "Caragh Marie Doyle"
    affiliation: "Department of Psychology, Maynooth University, Ireland"
  - name: "Cormac Monaghan"
    url: "https://c-monaghan.github.io/"
    orcid: "0000-0001-9012-3060"
    affiliation: "Department of Psychology, Maynooth University, Ireland"
  - name: "Noel Fitzpatrick"
    affiliation: " GradCAM, Technological University Dublin, Ireland"
  - name: "Richard A. P. Roche"
    affiliation: "Department of Psychology, Maynooth University, Ireland"
year: "2022"
publication: " Psychobiographical Illustrations on Meaning and Identity in Sociocultural Contexts"
toc: false
categories:
  - memory
  - journal article
---

## Citation (APA 7)

> Allen, A.P., Doyle, C., Doyle, C.M., Monaghan, C., Fitzpatrick, N., Roche, R.A.P. (2021). What We Talk About When We Talk About the Past: Discursive Psychological Analysis of Autobiographical Reminiscence in Older Irish Adults. In: Mayer, CH., Fouché, P.J., Van Niekerk, R. (eds) Psychobiographical Illustrations on Meaning and Identity in Sociocultural Contexts . Sociocultural Psychology of the Lifecourse . Palgrave Macmillan, Cham

## Abstract

Oral reminiscence about autobiographical memory may serve a number of discursive functions for older adults. In this article we use a discursive psychological approach to analyse reminiscence discussions with four older Irish adults. A number of functions of reminiscence are evident in the discussion, including narrative, offering/seeking guidance, and building rapport with others. However, other putative functions of reminiscence, such as death preparation or obsessive/escapist, were less evident at an explicit level. Furthermore, the function of maintaining a sense of self is perhaps oversimplified, as changes in sense of self were confronted across different life periods within participants’ autobiographical memories. Reminiscence segued between first person, interpersonal and broader societal accounts, and employed counterfactual scenarios as well as direct descriptions of memory. The current methodology and findings indicate the complexity of autobiographical memory and how it is employed, and have relevance for discursive analysis of biographical materials from famous individuals from the past. The application of discursive psychological analysis to autobiographical texts will allow for understanding of how remarkable individuals have attempted to position themselves “for posterity”.