---
title: "What We Talk About When We Talk About the Past: Discursive Psychological Analysis of Autobiographical Reminiscence in Older Irish Adults"
date: 2022-01-01
author: 
  - name: Andrew P. Allen
    affiliation: 
      - Department of Psychology, Maynooth University, Ireland
      - School of Nursing and Midwifery, Trinity College Dublin, Ireland
  - name: Caoilainn Doyle
    affiliation: Department of Psychology, Maynooth University, Ireland
  - name: Caragh Marie Doyle
    affiliation: Department of Psychology, Maynooth University, Ireland
  - name: Cormac Monaghan
    url: https://c-monaghan.github.io/
    orcid: 0000-0001-9012-3060
    affiliation: Department of Psychology, Maynooth University, Ireland
  - name: Noel Fitzpatrick
    affiliation:  GradCAM, Technological University Dublin, Ireland
  - name: Richard A. P. Roche
    affiliation: Department of Psychology, Maynooth University, Ireland
doi: 10.1007/978-3-030-81238-6_15
categories:
  - memory
  - journal article
pub-info:
  reference: >-
    Allen, A.P., Doyle, C., Doyle, C.M., <a href="https://github.com/C-Monaghan">Monaghan, C.</a>, Fitzpatrick, N., Roche, R.A.P. (2021). What we talk about when we talk about the past: Discursive psychological analysis of autobiographical reminiscence in older Irish adults. <em>Psychobiographical illustrations on meaning and identity in sociocultural contexts</em>, 327-344. <a href=https://doi.org/10.1007/978-3-030-81238-6_15><code>10.1007/978-3-030-81238-6_15</code></a>
---

## Abstract

Oral reminiscence about autobiographical memory may serve a number of discursive functions for older adults. In this article we use a discursive psychological approach to analyse reminiscence discussions with four older Irish adults. A number of functions of reminiscence are evident in the discussion, including narrative, offering/seeking guidance, and building rapport with others. However, other putative functions of reminiscence, such as death preparation or obsessive/escapist, were less evident at an explicit level. Furthermore, the function of maintaining a sense of self is perhaps oversimplified, as changes in sense of self were confronted across different life periods within participants’ autobiographical memories. Reminiscence segued between first person, interpersonal and broader societal accounts, and employed counterfactual scenarios as well as direct descriptions of memory. The current methodology and findings indicate the complexity of autobiographical memory and how it is employed, and have relevance for discursive analysis of biographical materials from famous individuals from the past. The application of discursive psychological analysis to autobiographical texts will allow for understanding of how remarkable individuals have attempted to position themselves “for posterity”.

## Citation

``` bibtex
@article{allen2021,
  title={What we talk about when we talk about the past: Discursive psychological analysis of autobiographical reminiscence in older Irish adults},
  author={Allen, Andrew P and Doyle, Caoilainn and Doyle, Caragh Marie and Monaghan, Cormac and Fitzpatrick, Noel and Roche, Richard AP},
  journal={Psychobiographical illustrations on meaning and identity in sociocultural contexts},
  pages={327--344},
  year={2021},
  publisher={Springer},
  doi={10.1007/978-3-030-81238-6_15}
}
```
