---
title: "Procrastination, depressive symptomatology, and loneliness in later life"
type: "article"
author:
  - name: "Cormac Monaghan"
    url: "https://c-monaghan.github.io/"
    orcid: "0000-0001-9012-3060"
    affiliation: 
      - "Hamilton Institute, Maynooth University, Ireland"
      - "Department of Psychology, Maynooth University, Ireland"
  - name: "Ione Avila-Palencia"
    orcid: "0000-0002-4353-2256"
    affiliation: 
      - "Centre for Public Health, Queens University, Ireland"
  - name: "S. Duke Han"
    orcid: "0000-0003-2453-9230"
    affiliation: "Department of Psychology, University of Southern California, CA, USA"
  - name: "Joanna McHugh Power"
    orcid: "0000-0002-7387-3107"
    affiliation: 
      - "Department of Psychology, Maynooth University, Ireland"
year: "2024"
publication: "Ageing and Mental Health"
doi: "https://doi.org/10.1080/13607863.2024.2345781"
toc: false
categories:
  - procrastination
  - structural equation modelling
  - journal article
keywords: 
  - health and retirement study
  - structural equation modelling
  - mediation
  - voluntary delay
  - mental health
github: "https://github.com/C-Monaghan/Procrastination_Predictors"
citation: 
  type: article-journal
  issued:
    year: 2024
    month: 05
    day: 02
  volume: 28
  issue: 9
  container-title: "Ageing and Mental Health"
  doi: "10.1080/13607863.2024.2345781"
---

## Citation (APA 7)

> Monaghan, C., Avila-Palencia, I., Han, S. D., & McHugh Power, J. (2024). Procrastination, depressive symptomatology, and loneliness in later life. Aging & Mental Health, 28(9), 1270–1277.

## Abstract

Procrastination is an almost universal behaviour and yet little research to date has focused on procrastination among older adults. The purpose of this study was to explore the potential association between age and procrastination, and the potential mediating roles of depressive symptomatology and loneliness.Structural equation modelling was applied to data from 1309 participants (aged 29–92) from two waves United States Health and Retirement Study (2016–2020). Within the model, sex, education, marital status, and job status were added as covariates. There was no statistically significant direct effect between age and procrastination ($\beta$ = 0.06, p = 0.106). However, an indirect effect was present via depressive symptomatology ($\beta$ = −0.40, p \< 0.001). No mediating effect of loneliness was observed ($\beta$ = − 0.01, p = 0.371). Subsequent analysis revealed that the symptoms, fatigue, loneliness, and lack of motivation significantly predicted procrastination. While age was not directly associated with procrastination, increasing age was associated with a decreased likelihood of depressive symptomatology, which was in turn associated with an increased likelihood of procrastination. Such findings indicates that age demonstrates no association with procrastination because of the suppressing effect of depressive symptomatology.
